### PR TITLE
Fix serialisation bug

### LINKED ISSUE #131: Error when reading tfevents files written with TensorBoardLogger v0.1.21
Hello, I updated `TensorboardLogger` to the latest `0.1.21` version, and the following minimum example doesn't work anymore:

```julia
using Logging
using TensorBoardLogger
using ValueHistories

logger = TBLogger("logs"; min_level=Logging.Info)

with_logger(logger) do
    @info "train" loss = 1.0
    @info "train" loss = 0.0
end

r = TBReader("logs1")
hist = MVHistory()

TensorBoardLogger.map_summaries(r) do tag, iter, val
    push!(hist, Symbol(tag), iter, val)
end
```

Here is the error:

```bash
ERROR: AssertionError: crc_data == crc_data_ck
Stacktrace:
 [1] read_event(f::IOStream)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:49
 [2] iterate(it::TensorBoardLogger.TBEventFileIterator, state::Int64)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:126
 [3] map_summaries(fun::var"#21#22", logdir::TBReader; purge::Bool, tags::Nothing, steps::Nothing, smart::Bool)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:270
 [4] map_summaries(fun::Function, logdir::TBReader)
   @ TensorBoardLogger ~/.julia/packages/TensorBoardLogger/LO5eP/src/Deserialization/deserialization.jl:248
```

Reading files written with an older version still works.
Am I missing something ?

ps: by the way, it seems that version `0.1.20` cannot be installed from the general registry for some reason (only from the github repository url)

### PR DESCRIPTION
**Pull request by JamieMair**
Closes https://github.com/JuliaLogging/TensorBoardLogger.jl/issues/131

See commits for explanation.

@nomadbl would you be able to review & merge this fix?

### CODE REVIEW

File: src/utils.jl [hunk 1]
```diff
@@ -9,7 +9,7 @@ end
 function serialize_proto(data)
     pb = PipeBuffer()
     encode(ProtoEncoder(pb), data)
-    pb.data
+    return view(pb.data, 1:pb.size) # Do not return additional zeros
```
Comment (nomadbl) [inline src/utils.jl]: @JamieMair 
This seems like the core of this PR (and the other changes are for reuse of this in other places).
But I can't understand the difference between this and the previous implementation.
Can you give a short explanation and links?

Overall the PR looks good I just want to do some due diligence

Comment (JamieMair) [reply src/utils.jl]: Under the hood, `ProtoBuf.jl` uses the function `maybe_ensure_room` ([link](https://github.com/JuliaIO/ProtoBuf.jl/blob/548017cb69778cb5f0cd1273b16507f81d64719e/src/codec/encode.jl#L7C2-L7C2)), which expands an IO buffer to potentially hold more bytes (padding zeros usually), so that new bytes can be written without unnecessary resizing. Sometimes this guesses the amount of bytes to expand by and overshoots (as with the example in https://github.com/JuliaLogging/TensorBoardLogger.jl/issues/131), but the padding bytes should not be written to the events file, as it causes parsing errors. 

In https://github.com/JuliaLogging/TensorBoardLogger.jl/issues/131, the size of an event wrote the size of the unpadded bytes to the file, but the when skipping past the actual payload, ran into the padded zero bytes and tried to read this as the checksum, which caused the crc error. Also the checksum should only be ran on the unpadded data.

I actually ran into this problem with the hparams implementation but didn't really understand why `serialize_proto` wouldn't work for my application, which is why I wrote the function with `take!`. Now that I know why it wasn't working, I figured I should also update the hparams implementation to use the updated `serialize_proto` function instead. The main difference between this and my old function is the `view` which avoids the extra allocation.

Comment (nomadbl) [reply src/utils.jl]: Lets change back to the `take!` version.
It looks like it does not allocate and we would avoid possible future breaking changes.

note:
I tested `take!` using
```julia
julia> using BenchmarkTools
julia> pb = PipeBuffer()
julia> write(pb, rand(1000))
julia> @benchmark take!(pb)
Time  (median):      37.376 ns
Memory estimate: 64 bytes, allocs estimate: 1.

julia> write(pb, rand(1000000))
julia> @benchmark take!(pb)
Time  (median):      36.753 ns
Memory estimate: 64 bytes, allocs estimate: 1.
```

Comment (nomadbl) [reply src/utils.jl]:
```suggestion
    return take!(pb) # Do not return additional zeros
```

**Review by nomadbl — APPROVED** [review]

**Comment by JamieMair** [comment]
@nomadbl I have taken the suggestion, thanks!
